imports:
- path: storage.jinja
resources:
- name: kubeflow
  properties:
    createPipelinePersistentStorage: true
    database:
      name: mlpipeline
    dbUser:
      user: root
    disks:
    - diskType: pd-standard
      sizeGb: 20
      usage: metadata-store
    - diskType: pd-standard
      sizeGb: 200
      usage: artifact-store
    enable_cloudsql: false
    zone: australia-southeast1-a
  type: storage.jinja
